name: Neotest-go GitHub Actions
on:
  push:
    branches:
      - master
  pull_request: ~
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v3
      - name: Check formatting
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
          args: --check .
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v3
      - name: Set up nvim    
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: Prepare dependencies
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter
          git clone --depth 1 https://github.com/nvim-neotest/neotest.git ~/.local/share/nvim/site/pack/vendor/start/neotest
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start
          nvim --headless -c 'TSInstallSync lua go | quit'
      - name: Run tests 
        run: |
          nvim --version
          nvim --headless -c ':PlenaryBustedDirectory lua/spec'

  release:
    name: release
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - check-formatting
      - tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  luarocks-upload:
    runs-on: ubuntu-22.04
    needs: release
    steps:
      - uses: actions/checkout@v3
      - name: Get Version 
        run: echo "LUAROCKS_VERSION=$(git fetch --tags; git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          dependencies: |
            plenary.nvim
            nvim-nio
            neotest
